apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-06T01:05:55Z"
  generation: 1
  labels:
    app: legacy-book-list-web
  name: legacy-book-list-web
  namespace: default
  resourceVersion: "27637"
  selfLink: /apis/apps/v1/namespaces/default/deployments/legacy-book-list-web
  uid: 60b879c7-0ea0-4572-9516-833bf0ec5c8d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: legacy-book-list-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacy-book-list-web
    spec:
      containers:
      - image: caprilespe/legacy-book-list-web:v1
        imagePullPolicy: IfNotPresent
        name: legacy-book-list-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-06T01:06:06Z"
    lastUpdateTime: "2021-08-06T01:06:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-06T01:05:55Z"
    lastUpdateTime: "2021-08-06T01:06:06Z"
    message: ReplicaSet "legacy-book-list-web-7597776887" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
